### PR TITLE
TUI Notifications

### LINKED ISSUE #143: Create notifications
They can be used to inform about process delete success/failure etc

### LINKED ISSUE #179: Send error notification to user if clipboard cannot be accessed
Currently clipboard is lazy initialized and it will kill app if we cannot access clipboard manager. Instead of failing we can send notification that clipboard is not working properly.

Must be done after https://github.com/jacek-kurlit/pik/issues/143

### PR DESCRIPTION
**Pull request by Nanashi-lab**
/closes #143 
/closes #179 

- Add a dedicated TUI notification overlay for `info`, `success`, and `error` messages, and moved user feedback out of the help footer.
- Surface process kill success/failure, daemon/search errors, explicit refresh completion all now go to notification TUI than relay on relying on footer text.
- Clipboard failures as notifications to the TUI instead of panicking
- Add configurable notification styling and timeout support through UIConfig, default_config.toml, and config merge coverage.
- Kept notifications intentionally lightweight: they replace each other, auto-dismiss after a timeout, 

Possible Issue 
- Long TUI notification messages are currently truncated (height 3).

Screenshot from 2026-04-08 09-53-42

### CODE REVIEW

**Comment by Nanashi-lab** [comment]
There are few minor stuff, like should the notification include more robust message with names/PID of the process, improvements in test, for multiple notifications, do we create multiple notifications, one after the other etc. The core should be ready for the review. Thank you.

**Comment by jacek-kurlit** [comment]
Hi!
Thanks for the PR.
Let me address some questions:
1. I think process kill message should contain pid and process name
2. Notification should be a bit bigger and it should have margin from borders
3. Probably only notification title should have color red/yellow/green and content should be default

I will review it more deeply soon.

Cheers!

File: src/config/ui.rs [hunk 1]
```diff
@@ -313,6 +315,39 @@ impl Default for PopupsTheme {
...
+    #[serde(default, with = "StyleDef")]
+    pub success: Style,
+    #[serde(default, with = "StyleDef")]
+    pub error: Style,
+    #[serde(default = "default_notification_timeout_ms")]
+    pub timeout_ms: u64,
+}
+
+const fn default_notification_timeout_ms() -> u64 {
+    2500
```
Comment (jacek-kurlit) [inline src/config/ui.rs]: Since our default config is always used, do we need this here?

File: src/config/ui.rs [hunk 2]
```diff
@@ -313,6 +315,39 @@ impl Default for PopupsTheme {
...
+}
+
+impl Default for NotificationsTheme {
```
Comment (jacek-kurlit) [inline src/config/ui.rs:351]: at this point since we have default embedded I wouldn't even bother with default implementations

File: src/config/ui.rs [hunk 3]
```diff
@@ -22,6 +22,8 @@ pub struct UIConfig {
     pub search_bar: SearchBarTheme,
     #[serde(default)]
     pub popups: PopupsTheme,
+    #[serde(default)]
+    pub notifications: NotificationsTheme,
```
Comment (jacek-kurlit) [inline src/config/ui.rs]: It should be called NotificationsConfig and contains timeout and theme fields

File: src/tui/components/processes_view.rs [hunk 4]
```diff
@@ -63,6 +69,7 @@ impl ProcessesViewComponent {
                 &ui_config.search_bar,
                 ui_config.icons.get_icons().search_prompt.as_str(),
             ),
+            show_refresh_result_notification: false,
```
Comment (jacek-kurlit) [inline src/tui/components/processes_view.rs]: Entire logic related with this field is not needed, just don't send any notification for refresh.
Current approach adds to many complexity and side effects

File: src/tui/components/processes_view.rs [hunk 5]
```diff
@@ -148,40 +161,108 @@ impl ProcessesViewComponent {
...
+fn update_refresh_notification_on_search_request(
+    show_refresh_result_notification: &mut bool,
+    triggered_by_refresh: bool,
+) {
+    if !triggered_by_refresh {
+        *show_refresh_result_notification = false;
+    }
+}
+
+fn notification_for_operation_result(
```
Comment (jacek-kurlit) [inline src/tui/components/processes_view.rs]: If you get rid of show_refresh_result_notification then this method can be removed

File: src/tui/components/processes_view.rs [hunk 6]
```diff
@@ -148,40 +161,108 @@ impl ProcessesViewComponent {
...
+                return KeyAction::Event(ComponentEvent::ShowNotification(Notification::error(
+                    format!("Failed to copy PID to clipboard: {err}"),
+                )));
+            }
         }
         KeyAction::Consumed
     }
 }
 
+fn update_refresh_notification_on_search_request(
```
Comment (jacek-kurlit) [inline src/tui/components/processes_view.rs]: I think this method will not be needed

**Review by jacek-kurlit — CHANGES_REQUESTED** [review]

**Comment by Nanashi-lab** [comment]
Most of the changes you requested are done. 

1) Process kill message success or failure now shows - name and PID
2) Notification is bigger with padding from the border. 
3) Notification title has color, content is default 
4) Changed name to NotificationConfig which now has timeout and theme fields
5) Removed notification of refresh

Screenshot from 2026-04-14 15-05-20


The change I did not make is removing `impl Default` -  NotificationConfig can get defaults directly from default_config.toml, having `impl Default` follows patterns from other ui configs.  

Currently even in default_config.toml, some of defaults are derived from these UI defaults. and a lot of tests use them, which can be updated to use the merged configs. I can remove all of (almost) of these  `impl Default` `serde(default)` move all of those to default_config.toml. Keeping partial defaults but not have defaults sounds not the best choices. Below is the list of all that would be removed and all that would be kept. 

Remove
- All #[serde(default)] usage in src/config/ui.rs
- All Default derives/impls for UI config/theme types in src/config/ui.rs  
- The default_notification_timeout_ms() helper
- Default on serde remote adapter enums/structs used only for fallback behavior

Keep
- All UI config structs/enums as the config schema
- IconsStruct::ascii() and IconsStruct::nerd_font_v3()
- IconConfig::get_icons()
- ASCII_CONFIG / NERD_FONT_V3_CONFIG
- Serde naming/alias behavior like rename_all = "snake_case" and enum aliases
- Remote serde adapter definitions (StyleDef, BorderTypeDef, AlignmentDef, TitlePositionDef) for format mapping

I am unsure if this the right method architecturally. If this is the way, I can make this part of this PR or I can make a separate PR first to remove all `impl Defaults` and `serde(defaults)` and then update this implementaton ?

**Review by jacek-kurlit — APPROVED** [review]

**Comment by jacek-kurlit** [comment]
I will think about those defaults later.
Thanks for the PR!
